name: Run npm ready on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run npm Command
        run: npm run ready

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m 'Run npm ready and update dist folder'
            git push https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/GSAStudentCouncil/gsa-bot.git HEAD:main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
